language: node_js
node_js:
  - "0.10"
before_install:
  - "mkdir node_modules"
  - "cd node_modules"
  - "git clone https://github.com/hudson-taylor/hudson-taylor.git"
  - "cd hudson-taylor"
  - "git checkout 2"
  - "npm install"
  - "cd ../.."
  - "npm install"
  - "npm run build"
services:
  - mongodb
